#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  May 13, 2022 04:01:09 PM UTC  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1060x575+1935+247
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1055
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MultiExplorer"
    vTcl:DefineAlias "$top" "Input_cpu" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m45 add command \
        -command {#} -label {Editar como JSON} 
    labelframe $top.lab46 \
        -foreground black -text Preferences -background $vTcl(actual_gui_bg) \
        -height 160 -highlightcolor black -width 460 
    vTcl:DefineAlias "$top.lab46" "LabelFrame_Preferences" vTcl:WidgetProc "Input_cpu" 1
    set site_3_0 $top.lab46
    ttk::combobox $site_3_0.tCo52 \
        -values {Sniper Verilator Outro {} {}} -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo52" "TCombobox_Simulator" vTcl:WidgetProc "Input_cpu" 1
    checkbutton $site_3_0.che53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Yes -variable che53 
    vTcl:DefineAlias "$site_3_0.che53" "Check_yes_DSE" vTcl:WidgetProc "Input_cpu" 1
    bind $site_3_0.che53 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Sim
Nao}
    }
    vTcl:copy_lock $site_3_0.che53
    label $site_3_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Simulator 
    vTcl:DefineAlias "$site_3_0.lab55" "Label_Simulator" vTcl:WidgetProc "Input_cpu" 1
    checkbutton $site_3_0.che57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text No 
    vTcl:DefineAlias "$site_3_0.che57" "Check_no_DSE" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text DSE 
    vTcl:DefineAlias "$site_3_0.lab59" "Label_DSE" vTcl:WidgetProc "Input_cpu" 1
    ttk::combobox $site_3_0.tCo81 \
        -values {clock test1 outro1} -textvariable combobox -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo81" "TCombobox_Benchmark" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Benchmark 
    vTcl:DefineAlias "$site_3_0.lab82" "Label_Benchmark" vTcl:WidgetProc "Input_cpu" 1
    place $site_3_0.tCo52 \
        -in $site_3_0 -x 0 -relx 0.284 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.489 -height 0 -relheight 0.169 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che53 \
        -in $site_3_0 -x 0 -relx 0.283 -y 0 -rely 0.563 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.144 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab55 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.25 -width 0 \
        -relwidth 0.192 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che57 \
        -in $site_3_0 -x 0 -relx 0.459 -y 0 -rely 0.563 -width 0 \
        -relwidth 0.146 -height 0 -relheight 0.144 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.087 -y 0 -rely 0.563 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo81 \
        -in $site_3_0 -x 0 -relx 0.284 -y 0 -rely 0.813 -width 0 \
        -relwidth 0.496 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.813 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab47 \
        -foreground black -text {General Modeling} \
        -background $vTcl(actual_gui_bg) -height 482 -highlightcolor black \
        -width 405 
    vTcl:DefineAlias "$top.lab47" "Labelframe_General_Modeling" vTcl:WidgetProc "Input_cpu" 1
    set site_3_0 $top.lab47
    ttk::label $site_3_0.tLa70 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text Core 
    vTcl:DefineAlias "$site_3_0.tLa70" "TLabel1" vTcl:WidgetProc "Input_cpu" 1
    ttk::label $site_3_0.tLa71 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text Frequency 
    vTcl:DefineAlias "$site_3_0.tLa71" "TLabel2" vTcl:WidgetProc "Input_cpu" 1
    ttk::label $site_3_0.tLa72 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text Memory 
    vTcl:DefineAlias "$site_3_0.tLa72" "TLabel3" vTcl:WidgetProc "Input_cpu" 1
    ttk::label $site_3_0.tLa74 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text Network 
    vTcl:DefineAlias "$site_3_0.tLa74" "TLabel4" vTcl:WidgetProc "Input_cpu" 1
    ttk::label $site_3_0.tLa75 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text Power 
    vTcl:DefineAlias "$site_3_0.tLa75" "TLabel5" vTcl:WidgetProc "Input_cpu" 1
    ttk::combobox $site_3_0.tCo76 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo76" "TCombobox2" vTcl:WidgetProc "Input_cpu" 1
    ttk::entry $site_3_0.tEn77 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn77" "TEntry1" vTcl:WidgetProc "Input_cpu" 1
    ttk::combobox $site_3_0.tCo83 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo83" "TCombobox4" vTcl:WidgetProc "Input_cpu" 1
    ttk::combobox $site_3_0.tCo84 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo84" "TCombobox5" vTcl:WidgetProc "Input_cpu" 1
    ttk::combobox $site_3_0.tCo85 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo85" "TCombobox6" vTcl:WidgetProc "Input_cpu" 1
    place $site_3_0.tLa70 \
        -in $site_3_0 -x 0 -relx 0.074 -y 0 -rely 0.122 -width 0 \
        -relwidth 0.103 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa71 \
        -in $site_3_0 -x 0 -relx 0.074 -y 0 -rely 0.224 -width 0 \
        -relwidth 0.202 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa72 \
        -in $site_3_0 -x 0 -relx 0.074 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.202 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa74 \
        -in $site_3_0 -x 0 -relx 0.074 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.177 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa75 \
        -in $site_3_0 -x 0 -relx 0.074 -y 0 -rely 0.549 -width 0 \
        -relwidth 0.177 -height 0 -relheight 0.039 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo76 \
        -in $site_3_0 -x 0 -relx 0.32 -y 0 -rely 0.122 -width 0 \
        -relwidth 0.436 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn77 \
        -in $site_3_0 -x 0 -relx 0.32 -y 0 -rely 0.224 -width 174 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo83 \
        -in $site_3_0 -x 0 -relx 0.32 -y 0 -rely 0.325 -width 0 \
        -relwidth 0.436 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo84 \
        -in $site_3_0 -x 0 -relx 0.32 -y 0 -rely 0.447 -width 0 \
        -relwidth 0.436 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo85 \
        -in $site_3_0 -x 0 -relx 0.32 -y 0 -rely 0.549 -width 0 \
        -relwidth 0.436 -height 0 -relheight 0.043 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab48 \
        -foreground black -text DSE -background $vTcl(actual_gui_bg) \
        -height 300 -highlightcolor black -width 459 
    vTcl:DefineAlias "$top.lab48" "Labelframe_DSE" vTcl:WidgetProc "Input_cpu" 1
    set site_3_0 $top.lab48
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {ORIG CORES} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_OrigCores" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {IP CORES} 
    vTcl:DefineAlias "$site_3_0.lab61" "Label_ipCores" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Max. Power Density} 
    vTcl:DefineAlias "$site_3_0.lab62" "Label_Max_Power" vTcl:WidgetProc "Input_cpu" 1
    entry $site_3_0.ent63 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$site_3_0.ent63" "Entry_min_origCores" vTcl:WidgetProc "Input_cpu" 1
    bind $site_3_0.ent63 <<SetBalloon>> {
        set ::vTcl::balloon::%W {de}
    }
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Maximum Area} 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_MaxArea" vTcl:WidgetProc "Input_cpu" 1
    entry $site_3_0.ent65 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 146 
    vTcl:DefineAlias "$site_3_0.ent65" "Entry_MaxPower" vTcl:WidgetProc "Input_cpu" 1
    bind $site_3_0.ent65 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Entry_MaxPower}
    }
    entry $site_3_0.ent66 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 146 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry_maximunArea" vTcl:WidgetProc "Input_cpu" 1
    entry $site_3_0.ent67 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 56 
    vTcl:DefineAlias "$site_3_0.ent67" "Entry_min_ipcores" vTcl:WidgetProc "Input_cpu" 1
    bind $site_3_0.ent67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {min}
    }
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text (W/mm²) 
    vTcl:DefineAlias "$site_3_0.lab68" "Label7" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text (mm²) 
    vTcl:DefineAlias "$site_3_0.lab69" "Label8" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab86 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text To 
    vTcl:DefineAlias "$site_3_0.lab86" "Label10" vTcl:WidgetProc "Input_cpu" 1
    label $site_3_0.lab87 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text To 
    vTcl:DefineAlias "$site_3_0.lab87" "Label11" vTcl:WidgetProc "Input_cpu" 1
    entry $site_3_0.ent88 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 66 
    vTcl:DefineAlias "$site_3_0.ent88" "Entry_max_origCores" vTcl:WidgetProc "Input_cpu" 1
    entry $site_3_0.ent89 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 66 
    vTcl:DefineAlias "$site_3_0.ent89" "Entry_max_ipcores" vTcl:WidgetProc "Input_cpu" 1
    bind $site_3_0.ent89 <<SetBalloon>> {
        set ::vTcl::balloon::%W {max}
    }
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.167 -width 0 \
        -relwidth 0.216 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.367 -width 0 \
        -relwidth 0.194 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.5 -width 0 \
        -relwidth 0.325 -height 0 -relheight 0.137 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent63 \
        -in $site_3_0 -x 0 -relx 0.437 -y 0 -rely 0.167 -width 56 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.065 -y 0 -rely 0.7 -width 0 \
        -relwidth 0.259 -height 0 -relheight 0.137 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 0 -relx 0.436 -y 0 -rely 0.533 -width 146 \
        -relwidth 0 -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 0 -relx 0.437 -y 0 -rely 0.733 -width 146 \
        -relwidth 0 -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 0 -relx 0.437 -y 0 -rely 0.367 -width 56 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.786 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.129 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.808 -y 0 -rely 0.733 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab86 \
        -in $site_3_0 -x 0 -relx 0.59 -y 0 -rely 0.167 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 0 -relx 0.59 -y 0 -rely 0.367 -width 0 \
        -relwidth 0.085 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent88 \
        -in $site_3_0 -x 0 -relx 0.721 -y 0 -rely 0.167 -width 66 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent89 \
        -in $site_3_0 -x 0 -relx 0.721 -y 0 -rely 0.367 -width 66 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    button $top.but49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Voltar 
    vTcl:DefineAlias "$top.but49" "Button1" vTcl:WidgetProc "Input_cpu" 1
    button $top.but51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Executar 
    vTcl:DefineAlias "$top.but51" "Button2" vTcl:WidgetProc "Input_cpu" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.066 -y 0 -rely 0.07 -width 0 -relwidth 0.434 \
        -height 0 -relheight 0.278 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.07 -width 0 -relwidth 0.382 \
        -height 0 -relheight 0.838 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.066 -y 0 -rely 0.383 -width 0 -relwidth 0.433 \
        -height 0 -relheight 0.522 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.05 -y 0 -rely 0.911 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 0 -relx 0.783 -y 0 -rely 0.911 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

