#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  May 13, 2022 03:54:46 PM UTC  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 712x479+286+165
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "inputGPU" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    labelframe $top.lab45 \
        -foreground black -text Preferences -background $vTcl(actual_gui_bg) \
        -height 152 -highlightcolor black -width 285 
    vTcl:DefineAlias "$top.lab45" "Labelframe1" vTcl:WidgetProc "inputGPU" 1
    set site_3_0 $top.lab45
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Simulator 
    vTcl:DefineAlias "$site_3_0.lab50" "Label12" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text DSE 
    vTcl:DefineAlias "$site_3_0.lab51" "Label13" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Application 
    vTcl:DefineAlias "$site_3_0.lab52" "Label14" vTcl:WidgetProc "inputGPU" 1
    ttk::combobox $site_3_0.tCo53 \
        -values GPGPUSIM -textvariable BoxSimulator_GPU -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo53" "Combobox_Simulator" vTcl:WidgetProc "inputGPU" 1
    checkbutton $site_3_0.che54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Yes -variable che54 
    vTcl:DefineAlias "$site_3_0.che54" "Checkbutton_DSE_Yes" vTcl:WidgetProc "inputGPU" 1
    checkbutton $site_3_0.che55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text No -variable Check_dse_no 
    vTcl:DefineAlias "$site_3_0.che55" "Checkbutton_DSE_No" vTcl:WidgetProc "inputGPU" 1
    ttk::combobox $site_3_0.tCo56 \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo56" "Combobox_Application" vTcl:WidgetProc "inputGPU" 1
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.277 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.105 -y 0 -rely 0.461 -width 0 \
        -relwidth 0.137 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.035 -y 0 -rely 0.724 -width 0 \
        -relwidth 0.277 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo53 \
        -in $site_3_0 -x 0 -relx 0.316 -y 0 -rely 0.263 -width 0 \
        -relwidth 0.481 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che54 \
        -in $site_3_0 -x 0 -relx 0.281 -y 0 -rely 0.461 -width 0 \
        -relwidth 0.235 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.che55 \
        -in $site_3_0 -x 0 -relx 0.561 -y 0 -rely 0.461 -width 0 \
        -relwidth 0.235 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo56 \
        -in $site_3_0 -x 0 -relx 0.316 -y 0 -rely 0.724 -width 0 \
        -relwidth 0.481 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab48 \
        -foreground black -text DSE -background $vTcl(actual_gui_bg) \
        -height 205 -highlightcolor black -width 290 
    vTcl:DefineAlias "$top.lab48" "Labelframe2" vTcl:WidgetProc "inputGPU" 1
    set site_3_0 $top.lab48
    label $site_3_0.lab74 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Orig Cores} 
    vTcl:DefineAlias "$site_3_0.lab74" "Label23" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab75 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {IP Cores} 
    vTcl:DefineAlias "$site_3_0.lab75" "Label24" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab76 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {MAX. Power
Density} 
    vTcl:DefineAlias "$site_3_0.lab76" "Label25" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab77 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {MAX. Area} 
    vTcl:DefineAlias "$site_3_0.lab77" "Label26" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab78 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Lithograph 
    vTcl:DefineAlias "$site_3_0.lab78" "Label27" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn79 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn79" "Entry_OrigCores_Min" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn80 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn80" "Entry_OrigCores_Max" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {To
} 
    vTcl:DefineAlias "$site_3_0.lab81" "Label28" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Orig Cores} 
    vTcl:DefineAlias "$site_3_0.lab82" "Label29" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Orig Cores} 
    vTcl:DefineAlias "$site_3_0.lab83" "Label30" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn84 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn84" "Entry_IpCores_Min" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab85 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text To 
    vTcl:DefineAlias "$site_3_0.lab85" "Label31" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn86 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn86" "Entry_IpCores_Max" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn87 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn87" "Entry_MaxPower" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn89 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn89" "Entry_Lithograph" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn90 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn90" "Entry_MaxArea" vTcl:WidgetProc "inputGPU" 1
    ttk::label $site_3_0.tLa91 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text (W/mm³) 
    vTcl:DefineAlias "$site_3_0.tLa91" "TLabel6" vTcl:WidgetProc "inputGPU" 1
    ttk::label $site_3_0.tLa92 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text (mm²) 
    vTcl:DefineAlias "$site_3_0.tLa92" "TLabel7" vTcl:WidgetProc "inputGPU" 1
    ttk::label $site_3_0.tLa93 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -relief flat -anchor w -justify left -text (nm) 
    vTcl:DefineAlias "$site_3_0.tLa93" "TLabel8" vTcl:WidgetProc "inputGPU" 1
    place $site_3_0.lab74 \
        -in $site_3_0 -x 0 -relx -0.552 -y 0 -rely -0.049 -width 0 \
        -relwidth 0.307 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 0 -relx 0.034 -y 0 -rely 0.293 -width 0 \
        -relwidth 0.238 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 0 -relx 0.034 -y 0 -rely 0.439 -width 0 \
        -relwidth 0.307 -height 0 -relheight 0.2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 0 -relx 0.069 -y 0 -rely 0.634 -width 0 \
        -relwidth 0.272 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 0 -relx 0.034 -y 0 -rely 0.78 -width 0 \
        -relwidth 0.307 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn79 \
        -in $site_3_0 -x 0 -relx 0.31 -y 0 -rely 0.146 -width 54 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn80 \
        -in $site_3_0 -x 0 -relx 0.69 -y 0 -rely 0.146 -width 54 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.134 -height 0 -relheight 0.151 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx -0.31 -y 0 -rely -0.146 -width 0 \
        -relwidth 0.252 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 0 -relx 0.034 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.272 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn84 \
        -in $site_3_0 -x 0 -relx 0.31 -y 0 -rely 0.293 -width 54 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab85 \
        -in $site_3_0 -x 0 -relx 0.517 -y 0 -rely 0.293 -width 0 \
        -relwidth 0.124 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn86 \
        -in $site_3_0 -x 0 -relx 0.69 -y 0 -rely 0.293 -width 54 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn87 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.488 -width 114 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn89 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.78 -width 114 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn90 \
        -in $site_3_0 -x 0 -relx 0.345 -y 0 -rely 0.634 -width 114 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa91 \
        -in $site_3_0 -x 0 -relx 0.759 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.214 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa92 \
        -in $site_3_0 -x 0 -relx 0.793 -y 0 -rely 0.634 -width 0 \
        -relwidth 0.145 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa93 \
        -in $site_3_0 -x 0 -relx 0.793 -y 0 -rely 0.78 -width 0 \
        -relwidth 0.145 -height 0 -relheight 0.093 -anchor nw \
        -bordermode ignore 
    labelframe $top.lab49 \
        -foreground black -text {General Modeling} \
        -background $vTcl(actual_gui_bg) -height 395 -highlightcolor black \
        -width 262 
    vTcl:DefineAlias "$top.lab49" "Labelframe3" vTcl:WidgetProc "inputGPU" 1
    set site_3_0 $top.lab49
    ttk::combobox $site_3_0.tCo57 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo57" "Combobox_model" vTcl:WidgetProc "inputGPU" 1
    ttk::combobox $site_3_0.tCo58 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo58" "Combobox_Clock" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn59 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn59" "Entry_SM" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn60 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn60" "Entry_shmensize" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn61 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn61" "entry_registers" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn62 \
        -foreground {} -background {} -takefocus {} -cursor xterm 
    vTcl:DefineAlias "$site_3_0.tEn62" "Entry_BlocksSm" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Model 
    vTcl:DefineAlias "$site_3_0.lab63" "Label15" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Clock 
    vTcl:DefineAlias "$site_3_0.lab64" "Label16" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab65 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text SM 
    vTcl:DefineAlias "$site_3_0.lab65" "Label17" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Shmem Size} 
    vTcl:DefineAlias "$site_3_0.lab66" "Label18" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab67 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Registers 
    vTcl:DefineAlias "$site_3_0.lab67" "Label19" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Blocks/SM 
    vTcl:DefineAlias "$site_3_0.lab68" "Label20" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab69 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Clock 
    vTcl:DefineAlias "$site_3_0.lab69" "Label21" vTcl:WidgetProc "inputGPU" 1
    ttk::entry $site_3_0.tEn71 \
        -foreground {} -background {} -takefocus {} -cursor fleur 
    vTcl:DefineAlias "$site_3_0.tEn71" "Entry_power" vTcl:WidgetProc "inputGPU" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Power 
    vTcl:DefineAlias "$site_3_0.lab73" "Label22" vTcl:WidgetProc "inputGPU" 1
    place $site_3_0.tCo57 \
        -in $site_3_0 -x 0 -relx 0.427 -y 0 -rely 0.107 -width 0 \
        -relwidth 0.523 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo58 \
        -in $site_3_0 -x 0 -relx 0.427 -y 0 -rely 0.213 -width 0 \
        -relwidth 0.523 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn59 \
        -in $site_3_0 -x 0 -relx 0.426 -y 0 -rely 0.32 -width 144 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn60 \
        -in $site_3_0 -x 0 -relx 0.426 -y 0 -rely 0.427 -width 144 \
        -relwidth 0 -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn61 \
        -in $site_3_0 -x 0 -relx 0.42 -y 0 -rely 0.533 -width 144 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn62 \
        -in $site_3_0 -x 0 -relx 0.42 -y 0 -rely 0.64 -width 144 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.213 -y 0 -rely 0.107 -width 0 \
        -relwidth 0.209 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx -0.177 -y 0 -rely 0.427 -width 0 \
        -relwidth 0.174 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 0 -relx 0.267 -y 0 -rely 0.32 -width 0 \
        -relwidth 0.137 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -y 0 -rely 0.43 -width 0 -relwidth 0.366 -height 0 \
        -relheight 0.056 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 0 -relx 0.076 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.29 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.076 -y 0 -rely 0.64 -width 0 \
        -relwidth 0.328 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 0 -relx 0.229 -y 0 -rely 0.213 -width 0 \
        -relwidth 0.187 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn71 \
        -in $site_3_0 -x 0 -relx 0.42 -y 0 -rely 0.72 -width 144 -relwidth 0 \
        -height 21 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.191 -y 0 -rely 0.72 -width 0 \
        -relwidth 0.149 -height 0 -relheight 0.056 -anchor nw \
        -bordermode ignore 
    button $top.but45 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Back 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "inputGPU" 1
    button $top.but46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Execute 
    vTcl:DefineAlias "$top.but46" "Button2" vTcl:WidgetProc "inputGPU" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.084 -width 0 -relwidth 0.4 \
        -height 0 -relheight 0.317 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.459 -width 0 -relwidth 0.407 \
        -height 0 -relheight 0.428 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.534 -y 0 -rely 0.063 -width 0 -relwidth 0.368 \
        -height 0 -relheight 0.825 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.07 -y 0 -rely 0.898 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.758 -y 0 -rely 0.898 -width 103 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

