#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  May 13, 2022 03:51:05 PM UTC  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 629x439+1972+266
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1055
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MultiExplorer"
    vTcl:DefineAlias "$top" "TelaInicial" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    vTcl:copy_lock $top
    labelframe $top.lab46 \
        -foreground black -text {Execution Flow} \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 430 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "TelaInicial" 1
    set site_3_0 $top.lab46
    button $site_3_0.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Run 
    vTcl:DefineAlias "$site_3_0.but47" "Button_fluxoDeExe" vTcl:WidgetProc "TelaInicial" 1
    vTcl:copy_lock $site_3_0.but47
    ttk::combobox $site_3_0.tCo48 \
        -values {Gpu Cpu Outros {}} -textvariable combobox -foreground {} \
        -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo48" "Combobox_ExecutionFlow" vTcl:WidgetProc "TelaInicial" 1
    vTcl:copy_lock $site_3_0.tCo48
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.599 -y 0 -rely 0.4 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo48 \
        -in $site_3_0 -x 0 -relx 0.177 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.392 -height 0 -relheight 0.413 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab46
    menu $top.m49 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m49 add cascade \
        -menu "$top.m49.men50" -label Menu 
    set site_3_0 $top.m49
    menu $site_3_0.men50 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $site_3_0.men50 add command \
        -command {#} -label Settings 
    $site_3_0.men50 add command \
        -command {#} -label Import 
    $top.m49 add cascade \
        -menu "$top.m49.men52" -label Tools 
    set site_3_0 $top.m49
    menu $site_3_0.men52 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text MultiExplorer.png 
    vTcl:DefineAlias "$top.lab54" "Label1" vTcl:WidgetProc "TelaInicial" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.134 -y 0 -rely 0.422 -width 0 -relwidth 0.717 \
        -height 0 -relheight 0.167 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.302 -y 0 -rely 0.044 -width 0 -relwidth 0.38 \
        -height 0 -relheight 0.313 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

