version: "3.3"

services:
    dev:
        stdin_open: true
        tty: true
        build: .
        env_file: .env
        environment:
            - DISPLAY=${DISPLAY}
        volumes:
            - .:/multiexplorer
            - /tmp/.X11-unix:/tmp/.X11-unix
        links:
            - sniper:sniper
        restart: always
        expose:
            - 22
        networks:
            - multiexplorernet
    sniper:
        stdin_open: true
        tty: true
        restart: always
        image: snipersim/snipersim
        hostname: sniper
        volumes:
            - ./rundir:/root/rundir
        expose:
            - 22
        environment:
            - DISPLAY=${DISPLAY}
        networks:
            - multiexplorernet

networks:
  multiexplorernet:
    driver: bridge
