#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  May 13, 2022 02:46:10 PM UTC  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m45" -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 832x543+1872+346
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3345 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MultiExplorer"
    vTcl:DefineAlias "$top" "exeSim" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m45 \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font TkMenuFont -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
    $top.m45 add command \
        -activebackground {} -activeforeground {} -background {} -command {#} \
        -font {} -foreground {} -label Inicio 
    labelframe $top.lab46 \
        -foreground black -text {Input Info} -background $vTcl(actual_gui_bg) \
        -height 160 -width 360 
    vTcl:DefineAlias "$top.lab46" "Labelframe1" vTcl:WidgetProc "exeSim" 1
    set site_3_0 $top.lab46
    button $site_3_0.but47 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Ver mais} 
    vTcl:DefineAlias "$site_3_0.but47" "Button1" vTcl:WidgetProc "exeSim" 1
    text $site_3_0.tex50 \
        -background $vTcl(actual_gui_bg) -font TkTextFont -foreground black \
        -height 114 -highlightcolor black -inactiveselectbackground #d9d9d9 \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 186 -wrap word 
    $site_3_0.tex50 configure -font "TkTextFont"
    $site_3_0.tex50 insert end text
    vTcl:DefineAlias "$site_3_0.tex50" "Text1" vTcl:WidgetProc "exeSim" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.692 -y 0 -rely 0.222 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex50 \
        -in $site_3_0 -x 0 -relx 0.083 -y 0 -rely 0.188 -width 0 \
        -relwidth 0.517 -height 0 -relheight 0.713 -anchor nw \
        -bordermode ignore 
    button $top.but48 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Parar 
    vTcl:DefineAlias "$top.but48" "Button2" vTcl:WidgetProc "exeSim" 1
    frame $top.fra51 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -width 215 
    vTcl:DefineAlias "$top.fra51" "Frame1" vTcl:WidgetProc "exeSim" 1
    set site_3_0 $top.fra51
    label $site_3_0.lab54 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -text {Sniper } 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1" vTcl:WidgetProc "exeSim" 1
    ttk::progressbar $site_3_0.tPr56 \
        -length 100 
    vTcl:DefineAlias "$site_3_0.tPr56" "TProgressbar1" vTcl:WidgetProc "exeSim" 1
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.14 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.693 -height 0 -relheight 0.413 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tPr56 \
        -in $site_3_0 -x 0 -relx 0.233 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.465 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
    frame $top.fra53 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -width 235 
    vTcl:DefineAlias "$top.fra53" "Frame2" vTcl:WidgetProc "exeSim" 1
    set site_3_0 $top.fra53
    label $site_3_0.lab57 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -text McPat 
    vTcl:DefineAlias "$site_3_0.lab57" "Label2" vTcl:WidgetProc "exeSim" 1
    ttk::progressbar $site_3_0.tPr58 \
        -length 100 
    vTcl:DefineAlias "$site_3_0.tPr58" "TProgressbar2" vTcl:WidgetProc "exeSim" 1
    place $site_3_0.lab57 \
        -in $site_3_0 -x 0 -relx 0.426 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.166 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tPr58 \
        -in $site_3_0 -x 0 -relx 0.298 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.426 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
    frame $top.fra59 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -width 205 
    vTcl:DefineAlias "$top.fra59" "Frame3" vTcl:WidgetProc "exeSim" 1
    set site_3_0 $top.fra59
    label $site_3_0.lab60 \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -text DSE 
    vTcl:DefineAlias "$site_3_0.lab60" "Label3" vTcl:WidgetProc "exeSim" 1
    ttk::progressbar $site_3_0.tPr61 \
        -length 100 
    vTcl:DefineAlias "$site_3_0.tPr61" "TProgressbar3" vTcl:WidgetProc "exeSim" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.439 -y 0 -rely 0.133 -width 0 \
        -relwidth 0.19 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tPr61 \
        -in $site_3_0 -x 0 -relx 0.293 -y 0 -rely 0.667 -width 0 \
        -relwidth 0.488 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
    button $top.but62 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Ver resultados} 
    vTcl:DefineAlias "$top.but62" "Button3" vTcl:WidgetProc "exeSim" 1
    button $top.but63 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Ver Resultados} 
    vTcl:DefineAlias "$top.but63" "Button4" vTcl:WidgetProc "exeSim" 1
    button $top.but64 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Ver Resultados} 
    vTcl:DefineAlias "$top.but64" "Button5" vTcl:WidgetProc "exeSim" 1
    button $top.but65 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Executar 
    vTcl:DefineAlias "$top.but65" "Button6" vTcl:WidgetProc "exeSim" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.048 -y 0 -rely 0.076 -width 0 -relwidth 0.433 \
        -height 0 -relheight 0.295 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 0 -relx 0.072 -y 0 -rely 0.847 -anchor nw \
        -bordermode ignore 
    place $top.fra51 \
        -in $top -x 0 -relx 0.072 -y 0 -rely 0.479 -width 0 -relwidth 0.258 \
        -height 0 -relheight 0.138 -anchor nw -bordermode ignore 
    place $top.fra53 \
        -in $top -x 0 -relx 0.373 -y 0 -rely 0.479 -width 0 -relwidth 0.282 \
        -height 0 -relheight 0.138 -anchor nw -bordermode ignore 
    place $top.fra59 \
        -in $top -x 0 -relx 0.685 -y 0 -rely 0.479 -width 0 -relwidth 0.246 \
        -height 0 -relheight 0.138 -anchor nw -bordermode ignore 
    place $top.but62 \
        -in $top -x 0 -relx 0.132 -y 0 -rely 0.626 -anchor nw \
        -bordermode ignore 
    place $top.but63 \
        -in $top -x 0 -relx 0.445 -y 0 -rely 0.626 -width 113 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but64 \
        -in $top -x 0 -relx 0.745 -y 0 -rely 0.626 -anchor nw \
        -bordermode ignore 
    place $top.but65 \
        -in $top -x 0 -relx 0.841 -y 0 -rely 0.847 -width 73 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

