#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 13, 2022 02:46:10 PM UTC  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Execution_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = exeSim (root)
    Execution_support.init(root, top)
    root.mainloop()

w = None
def create_exeSim(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_exeSim(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = exeSim (w)
    Execution_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_exeSim():
    global w
    w.destroy()
    w = None

class exeSim:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("832x543+1872+346")
        top.minsize(1, 1)
        top.maxsize(3345, 1050)
        top.resizable(1,  1)
        top.title("MultiExplorer")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.menubar.add_command(
                label="Inicio")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.048, rely=0.076, relheight=0.295
                , relwidth=0.433)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(text='''Input Info''')
        self.Labelframe1.configure(cursor="fleur")

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.692, rely=0.225, height=33, width=88
                , bordermode='ignore')
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Ver mais''')

        self.Text1 = tk.Text(self.Labelframe1)
        self.Text1.place(relx=0.083, rely=0.188, relheight=0.713, relwidth=0.517
                , bordermode='ignore')
        self.Text1.configure(background="#d9d9d9")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(inactiveselectbackground="#d9d9d9")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.072, rely=0.847, height=33, width=64)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(text='''Parar''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.072, rely=0.479, relheight=0.138
                , relwidth=0.258)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.14, rely=0.133, height=31, width=149)
        self.Label1.configure(cursor="fleur")
        self.Label1.configure(text='''Sniper''')

        self.TProgressbar1 = ttk.Progressbar(self.Frame1)
        self.TProgressbar1.place(relx=0.233, rely=0.667, relwidth=0.465
                , relheight=0.0, height=19)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.373, rely=0.479, relheight=0.138
                , relwidth=0.282)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.426, rely=0.133, height=21, width=39)
        self.Label2.configure(text='''McPat''')

        self.TProgressbar2 = ttk.Progressbar(self.Frame2)
        self.TProgressbar2.place(relx=0.298, rely=0.667, relwidth=0.426
                , relheight=0.0, height=19)

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.685, rely=0.479, relheight=0.138
                , relwidth=0.246)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(cursor="fleur")

        self.Label3 = tk.Label(self.Frame3)
        self.Label3.place(relx=0.439, rely=0.133, height=21, width=39)
        self.Label3.configure(text='''DSE''')

        self.TProgressbar3 = ttk.Progressbar(self.Frame3)
        self.TProgressbar3.place(relx=0.293, rely=0.667, relwidth=0.488
                , relheight=0.0, height=19)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.132, rely=0.626, height=33, width=124)
        self.Button3.configure(borderwidth="2")
        self.Button3.configure(text='''Ver resultados''')

        self.Button4 = tk.Button(top)
        self.Button4.place(relx=0.445, rely=0.626, height=33, width=113)
        self.Button4.configure(borderwidth="2")
        self.Button4.configure(text='''Ver Resultados''')

        self.Button5 = tk.Button(top)
        self.Button5.place(relx=0.745, rely=0.626, height=33, width=128)
        self.Button5.configure(borderwidth="2")
        self.Button5.configure(text='''Ver Resultados''')

        self.Button6 = tk.Button(top)
        self.Button6.place(relx=0.841, rely=0.847, height=33, width=73)
        self.Button6.configure(borderwidth="2")
        self.Button6.configure(text='''Executar''')

if __name__ == '__main__':
    vp_start_gui()





