#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 13, 2022 01:49:06 PM UTC  platform: Linux
#    May 13, 2022 03:25:00 PM UTC  platform: Linux
#    May 13, 2022 03:54:53 PM UTC  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global Check_dse_no
    Check_dse_no = tk.IntVar()
    global BoxSimulator_GPU
    BoxSimulator_GPU = tk.StringVar()
    global che54
    che54 = tk.IntVar()
    global che55
    che55 = tk.IntVar()
    global combobox
    combobox = tk.StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import inputGPU
    inputGPU.vp_start_gui()





