#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    May 13, 2022 03:54:46 PM UTC  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import inputGPU_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    inputGPU_support.set_Tk_var()
    top = inputGPU (root)
    inputGPU_support.init(root, top)
    root.mainloop()

w = None
def create_inputGPU(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_inputGPU(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    inputGPU_support.set_Tk_var()
    top = inputGPU (w)
    inputGPU_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_inputGPU():
    global w
    w.destroy()
    w = None

class inputGPU:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("712x479+286+165")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("MultiExplorer")
        top.configure(highlightcolor="black")

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.07, rely=0.084, relheight=0.317
                , relwidth=0.4)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(text='''Preferences''')

        self.Label12 = tk.Label(self.Labelframe1)
        self.Label12.place(relx=0.035, rely=0.263, height=21, width=79
                , bordermode='ignore')
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(text='''Simulator''')

        self.Label13 = tk.Label(self.Labelframe1)
        self.Label13.place(relx=0.105, rely=0.461, height=21, width=39
                , bordermode='ignore')
        self.Label13.configure(activebackground="#f9f9f9")
        self.Label13.configure(text='''DSE''')

        self.Label14 = tk.Label(self.Labelframe1)
        self.Label14.place(relx=0.035, rely=0.724, height=21, width=79
                , bordermode='ignore')
        self.Label14.configure(activebackground="#f9f9f9")
        self.Label14.configure(text='''Application''')

        self.Combobox_Simulator = ttk.Combobox(self.Labelframe1)
        self.Combobox_Simulator.place(relx=0.316, rely=0.263, relheight=0.138
                , relwidth=0.481, bordermode='ignore')
        self.value_list = ['GPGPUSIM',]
        self.Combobox_Simulator.configure(values=self.value_list)
        self.Combobox_Simulator.configure(textvariable=inputGPU_support.BoxSimulator_GPU)
        self.Combobox_Simulator.configure(takefocus="")

        self.Checkbutton_DSE_Yes = tk.Checkbutton(self.Labelframe1)
        self.Checkbutton_DSE_Yes.place(relx=0.281, rely=0.461, relheight=0.151
                , relwidth=0.235, bordermode='ignore')
        self.Checkbutton_DSE_Yes.configure(activebackground="#f9f9f9")
        self.Checkbutton_DSE_Yes.configure(justify='left')
        self.Checkbutton_DSE_Yes.configure(text='''Yes''')
        self.Checkbutton_DSE_Yes.configure(variable=inputGPU_support.che54)

        self.Checkbutton_DSE_No = tk.Checkbutton(self.Labelframe1)
        self.Checkbutton_DSE_No.place(relx=0.561, rely=0.461, relheight=0.151
                , relwidth=0.235, bordermode='ignore')
        self.Checkbutton_DSE_No.configure(activebackground="#f9f9f9")
        self.Checkbutton_DSE_No.configure(justify='left')
        self.Checkbutton_DSE_No.configure(text='''No''')
        self.Checkbutton_DSE_No.configure(variable=inputGPU_support.Check_dse_no)

        self.Combobox_Application = ttk.Combobox(self.Labelframe1)
        self.Combobox_Application.place(relx=0.316, rely=0.724, relheight=0.138
                , relwidth=0.481, bordermode='ignore')
        self.Combobox_Application.configure(takefocus="")

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.07, rely=0.459, relheight=0.428
                , relwidth=0.407)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(text='''DSE''')

        self.Label23 = tk.Label(self.Labelframe2)
        self.Label23.place(relx=-0.552, rely=-0.049, height=21, width=89
                , bordermode='ignore')
        self.Label23.configure(activebackground="#f9f9f9")
        self.Label23.configure(text='''Orig Cores''')

        self.Label24 = tk.Label(self.Labelframe2)
        self.Label24.place(relx=0.034, rely=0.293, height=21, width=69
                , bordermode='ignore')
        self.Label24.configure(activebackground="#f9f9f9")
        self.Label24.configure(text='''IP Cores''')

        self.Label25 = tk.Label(self.Labelframe2)
        self.Label25.place(relx=0.034, rely=0.439, height=41, width=89
                , bordermode='ignore')
        self.Label25.configure(activebackground="#f9f9f9")
        self.Label25.configure(text='''MAX. Power
Density''')

        self.Label26 = tk.Label(self.Labelframe2)
        self.Label26.place(relx=0.069, rely=0.634, height=31, width=79
                , bordermode='ignore')
        self.Label26.configure(activebackground="#f9f9f9")
        self.Label26.configure(text='''MAX. Area''')

        self.Label27 = tk.Label(self.Labelframe2)
        self.Label27.place(relx=0.034, rely=0.78, height=31, width=89
                , bordermode='ignore')
        self.Label27.configure(activebackground="#f9f9f9")
        self.Label27.configure(text='''Lithograph''')

        self.Entry_OrigCores_Min = ttk.Entry(self.Labelframe2)
        self.Entry_OrigCores_Min.place(relx=0.31, rely=0.146, relheight=0.102
                , relwidth=0.186, bordermode='ignore')
        self.Entry_OrigCores_Min.configure(takefocus="")
        self.Entry_OrigCores_Min.configure(cursor="xterm")

        self.Entry_OrigCores_Max = ttk.Entry(self.Labelframe2)
        self.Entry_OrigCores_Max.place(relx=0.69, rely=0.146, relheight=0.102
                , relwidth=0.186, bordermode='ignore')
        self.Entry_OrigCores_Max.configure(takefocus="")
        self.Entry_OrigCores_Max.configure(cursor="xterm")

        self.Label28 = tk.Label(self.Labelframe2)
        self.Label28.place(relx=0.517, rely=0.146, height=31, width=39
                , bordermode='ignore')
        self.Label28.configure(activebackground="#f9f9f9")
        self.Label28.configure(cursor="fleur")
        self.Label28.configure(text='''To''')

        self.Label29 = tk.Label(self.Labelframe2)
        self.Label29.place(relx=-0.31, rely=-0.146, height=21, width=73
                , bordermode='ignore')
        self.Label29.configure(activebackground="#f9f9f9")
        self.Label29.configure(text='''Orig Cores''')

        self.Label30 = tk.Label(self.Labelframe2)
        self.Label30.place(relx=0.034, rely=0.146, height=21, width=79
                , bordermode='ignore')
        self.Label30.configure(activebackground="#f9f9f9")
        self.Label30.configure(text='''Orig Cores''')

        self.Entry_IpCores_Min = ttk.Entry(self.Labelframe2)
        self.Entry_IpCores_Min.place(relx=0.31, rely=0.293, relheight=0.102
                , relwidth=0.186, bordermode='ignore')
        self.Entry_IpCores_Min.configure(takefocus="")
        self.Entry_IpCores_Min.configure(cursor="xterm")

        self.Label31 = tk.Label(self.Labelframe2)
        self.Label31.place(relx=0.517, rely=0.293, height=21, width=36
                , bordermode='ignore')
        self.Label31.configure(activebackground="#f9f9f9")
        self.Label31.configure(text='''To''')

        self.Entry_IpCores_Max = ttk.Entry(self.Labelframe2)
        self.Entry_IpCores_Max.place(relx=0.69, rely=0.293, relheight=0.102
                , relwidth=0.186, bordermode='ignore')
        self.Entry_IpCores_Max.configure(takefocus="")
        self.Entry_IpCores_Max.configure(cursor="xterm")

        self.Entry_MaxPower = ttk.Entry(self.Labelframe2)
        self.Entry_MaxPower.place(relx=0.345, rely=0.488, relheight=0.102
                , relwidth=0.393, bordermode='ignore')
        self.Entry_MaxPower.configure(takefocus="")
        self.Entry_MaxPower.configure(cursor="xterm")

        self.Entry_Lithograph = ttk.Entry(self.Labelframe2)
        self.Entry_Lithograph.place(relx=0.345, rely=0.78, relheight=0.102
                , relwidth=0.393, bordermode='ignore')
        self.Entry_Lithograph.configure(takefocus="")
        self.Entry_Lithograph.configure(cursor="xterm")

        self.Entry_MaxArea = ttk.Entry(self.Labelframe2)
        self.Entry_MaxArea.place(relx=0.345, rely=0.634, relheight=0.102
                , relwidth=0.393, bordermode='ignore')
        self.Entry_MaxArea.configure(takefocus="")
        self.Entry_MaxArea.configure(cursor="xterm")

        self.TLabel6 = ttk.Label(self.Labelframe2)
        self.TLabel6.place(relx=0.759, rely=0.488, height=19, width=62
                , bordermode='ignore')
        self.TLabel6.configure(background="#d9d9d9")
        self.TLabel6.configure(foreground="#000000")
        self.TLabel6.configure(relief="flat")
        self.TLabel6.configure(anchor='w')
        self.TLabel6.configure(justify='left')
        self.TLabel6.configure(text='''(W/mm³)''')

        self.TLabel7 = ttk.Label(self.Labelframe2)
        self.TLabel7.place(relx=0.793, rely=0.634, height=19, width=42
                , bordermode='ignore')
        self.TLabel7.configure(background="#d9d9d9")
        self.TLabel7.configure(foreground="#000000")
        self.TLabel7.configure(relief="flat")
        self.TLabel7.configure(anchor='w')
        self.TLabel7.configure(justify='left')
        self.TLabel7.configure(text='''(mm²)''')

        self.TLabel8 = ttk.Label(self.Labelframe2)
        self.TLabel8.place(relx=0.793, rely=0.78, height=19, width=42
                , bordermode='ignore')
        self.TLabel8.configure(background="#d9d9d9")
        self.TLabel8.configure(foreground="#000000")
        self.TLabel8.configure(relief="flat")
        self.TLabel8.configure(anchor='w')
        self.TLabel8.configure(justify='left')
        self.TLabel8.configure(text='''(nm)''')

        self.Labelframe3 = tk.LabelFrame(top)
        self.Labelframe3.place(relx=0.534, rely=0.063, relheight=0.825
                , relwidth=0.368)
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(text='''General Modeling''')

        self.Combobox_model = ttk.Combobox(self.Labelframe3)
        self.Combobox_model.place(relx=0.427, rely=0.106, relheight=0.056
                , relwidth=0.523, bordermode='ignore')
        self.Combobox_model.configure(textvariable=inputGPU_support.combobox)
        self.Combobox_model.configure(takefocus="")

        self.Combobox_Clock = ttk.Combobox(self.Labelframe3)
        self.Combobox_Clock.place(relx=0.427, rely=0.213, relheight=0.056
                , relwidth=0.523, bordermode='ignore')
        self.Combobox_Clock.configure(textvariable=inputGPU_support.combobox)
        self.Combobox_Clock.configure(takefocus="")

        self.Entry_SM = ttk.Entry(self.Labelframe3)
        self.Entry_SM.place(relx=0.427, rely=0.319, relheight=0.053
                , relwidth=0.55, bordermode='ignore')
        self.Entry_SM.configure(takefocus="")
        self.Entry_SM.configure(cursor="xterm")

        self.Entry_shmensize = ttk.Entry(self.Labelframe3)
        self.Entry_shmensize.place(relx=0.427, rely=0.428, relheight=0.053
                , relwidth=0.55, bordermode='ignore')
        self.Entry_shmensize.configure(takefocus="")
        self.Entry_shmensize.configure(cursor="fleur")

        self.entry_registers = ttk.Entry(self.Labelframe3)
        self.entry_registers.place(relx=0.42, rely=0.534, relheight=0.053
                , relwidth=0.55, bordermode='ignore')
        self.entry_registers.configure(takefocus="")
        self.entry_registers.configure(cursor="fleur")

        self.Entry_BlocksSm = ttk.Entry(self.Labelframe3)
        self.Entry_BlocksSm.place(relx=0.42, rely=0.641, relheight=0.053
                , relwidth=0.55, bordermode='ignore')
        self.Entry_BlocksSm.configure(takefocus="")
        self.Entry_BlocksSm.configure(cursor="xterm")

        self.Label15 = tk.Label(self.Labelframe3)
        self.Label15.place(relx=0.214, rely=0.106, height=22, width=55
                , bordermode='ignore')
        self.Label15.configure(activebackground="#f9f9f9")
        self.Label15.configure(text='''Model''')

        self.Label16 = tk.Label(self.Labelframe3)
        self.Label16.place(relx=-0.176, rely=0.428, height=22, width=45
                , bordermode='ignore')
        self.Label16.configure(activebackground="#f9f9f9")
        self.Label16.configure(text='''Clock''')

        self.Label17 = tk.Label(self.Labelframe3)
        self.Label17.place(relx=0.267, rely=0.319, height=23, width=36
                , bordermode='ignore')
        self.Label17.configure(activebackground="#f9f9f9")
        self.Label17.configure(text='''SM''')

        self.Label18 = tk.Label(self.Labelframe3)
        self.Label18.place(relx=0.0, rely=0.43, height=22, width=96
                , bordermode='ignore')
        self.Label18.configure(activebackground="#f9f9f9")
        self.Label18.configure(text='''Shmem Size''')

        self.Label19 = tk.Label(self.Labelframe3)
        self.Label19.place(relx=0.076, rely=0.534, height=22, width=76
                , bordermode='ignore')
        self.Label19.configure(activebackground="#f9f9f9")
        self.Label19.configure(text='''Registers''')

        self.Label20 = tk.Label(self.Labelframe3)
        self.Label20.place(relx=0.076, rely=0.641, height=22, width=86
                , bordermode='ignore')
        self.Label20.configure(activebackground="#f9f9f9")
        self.Label20.configure(text='''Blocks/SM''')

        self.Label21 = tk.Label(self.Labelframe3)
        self.Label21.place(relx=0.229, rely=0.213, height=22, width=49
                , bordermode='ignore')
        self.Label21.configure(activebackground="#f9f9f9")
        self.Label21.configure(text='''Clock''')

        self.Entry_power = ttk.Entry(self.Labelframe3)
        self.Entry_power.place(relx=0.42, rely=0.719, relheight=0.053
                , relwidth=0.55, bordermode='ignore')
        self.Entry_power.configure(takefocus="")
        self.Entry_power.configure(cursor="fleur")

        self.Label22 = tk.Label(self.Labelframe3)
        self.Label22.place(relx=0.191, rely=0.719, height=23, width=39
                , bordermode='ignore')
        self.Label22.configure(activebackground="#f9f9f9")
        self.Label22.configure(text='''Power''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.07, rely=0.898, height=33, width=62)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(text='''Back''')

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.758, rely=0.898, height=33, width=103)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(text='''Execute''')

if __name__ == '__main__':
    vp_start_gui()





