#!/bin/bash
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.large-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.2xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.4xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.8xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.12xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5n.24xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.large-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.2xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/m5dn.24xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.large-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.2xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.4xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.9xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.12xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.18xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5.24xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.large-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.2xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.4xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.9xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/c5n.18xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.large-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.2xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.4xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.8xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.12xlarge-26.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-0.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-1.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-2.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-3.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-4.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-5.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-6.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-7.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-8.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-9.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-10.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-11.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-12.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-13.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-14.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-15.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-16.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-17.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-18.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-19.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-20.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-21.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-22.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-23.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-24.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-25.json
python MultiExplorer/src/MultiExplorer.py gerarinputs/r5.24xlarge-26.json
echo "FIM"